# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: TTLock2MQTT
version: "0.8"
slug: ttlock2mqtt
description: Connection between TTLock devices with Home Assistant using MQTT
url: "https://github.com/leofig-rj/tonyldo-hassio-addons"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
services:
  - mqtt:need
init: false
map:
  - share:rw
options:
  ttlockclientid: "TTLOCK CLOUD CLIENT ID"
  ttlockclientsecret: "TTLOCK CLOUD CLIENT SECRET"
  ttlockuser: "TTLOCK CLOUD USER"
  ttlockhash: "TTLOCK CLOUD HASH"
  publishstatedelay: 60
  publishbatterydelay: 300
  loglevel: "INFO"
schema:
  ttlockclientid: "str"
  ttlockclientsecret: "str"
  ttlockuser: "str"
  ttlockhash: "str"
  publishstatedelay: "int?"
  publishbatterydelay: "int?"
  loglevel: "list(DEBUG|INFO|WARNING|ERROR)?"
  maxthreads: "int?"
